# Generated by Django 4.0.1 on 2022-01-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventtype',
            unique_together={('category', 'name')},
        ),
    ]
