# Generated by Django 4.0.1 on 2022-01-15 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_eventtype_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('application__first_name', 'uuid'), 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='session',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Application'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
